# Generated by Django 5.0.4 on 2024-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_memory_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
